name: flutter_meta_share_example
description: Demonstrates how to use the flutter_meta_share plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  share: ^2.0.4
  path_provider: ^2.0.9
  video_player: ^2.3.0
  flutter_meta_share:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/video/